### ISSUE TITLE
question: will this work for a matrix setup

### ISSUE THREAD

**Issue by ReenigneArcher** [yogeshlonkar/wait-for-jobs#68]
Just a simple question, will this work for a matrix setup?

I have a matrix of 6 jobs to run. Currently, I have the matrix set to only run one at a time, because the matrix pushes to my repos and if they run simultaneously there will be conflicts.

But I want to start all the matrix jobs simultaneously, so I don't have to wait for runners to become available as the push events cause workflows to kick off in each repo, and then I am quickly out of available runners.

**Comment by yogeshlonkar** [comment]
@ReenigneArcher  If I understand correctly you want all of the matrix jobs to start simultaneously but the push step to be done one at a time by each matrix job. In this case you can use set `jobs` input to the previous job's name. Some what like below

```yaml
jobs:
  matrix-job:
    name: Matrix Job / ${{ matrix.input.name }} # this is the name which will be searched
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input: [{ name: 'x', your-arg: 'x', depends: '' }, { name: 'y', your-arg: 'y', depends: 'Matrix Job / x' }, { name: 'z', your-arg: 'z', depends: 'Matrix Job / y' }]
    steps:
  steps:
  # steps before waiting
  - uses: yogeshlonkar/wait-for-jobs@v0
    with:
      jobs: ${{ matrix.input.depends }}
  # rest of your steps
```

I've not tested this but logically this should work
